# Generated by Django 4.1.2 on 2022-10-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelauto',
            old_name='brand_id',
            new_name='brand',
        ),
    ]
