# Generated by Django 4.1.2 on 2022-10-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_brand_id_modelauto_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandauto',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='modelauto',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
