# Generated by Django 4.1.2 on 2022-10-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_brandauto_name_alter_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandauto',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='modelauto',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
