# Generated by Django 4.1 on 2022-10-17 13:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brandauto')),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.color')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.modelauto')),
            ],
        ),
    ]
