# Generated by Django 4.1 on 2022-10-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='color_id',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
